services:
  db:
    image: postgres:14
    container_name: db14_examen
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    restart: always       # se inicia como servicio
    volumes:
      - db14_examen-data:/var/lib/postgresql/data
    networks:
      - odoo-net_examen

  odoo16: 
    image: odoo:16
    container_name: odoo16_examen
    depends_on:
      - db    #el nombre del servicio. Odoo espera a que se inicie
    environment:
      HOST: db    #el nombre del servicio, no del contenedor
      USER: admin
      PASSWORD: admin
    ports:
      - "8089:8069"    # puerto del HOST: puerto del contenedor
    volumes:
      - odoo16_examen-data:/var/lib/odoo       #mapeo en el directorio de datos de odoo del contenedor. Para tener PERSISTENCIA
      - ./config_odoo:/etc/odoo          #mapeo en el directorio de configuraci√≥n del contenedor
      - ./custom-addons:/mnt/extra-addons #mapeo en el directorio local para personalizaciones
      - ./logs:/var/log/odoo            #mapeo de los log de odoo
    networks:
      - odoo-net_examen

volumes:
  db14_examen-data:
  odoo16_examen-data:

networks:
  odoo-net_examen:



